version: '3'
services:
  shared:
    build: ./shared
    image: dogada/microchain_shared
  api:
    build: ./api
    image: dogada/microchain_api
  webapp:
    build: ./webapp
    image: dogada/microchain_webapp
  