swagger: "2.0"
info:
  version: "0.0.1"
  title: MicroChain API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /transactions:
    x-swagger-router-controller: transactions
    get:
      description: Returns list of transactions for an address
      parameters:
        - name: account
          in: query
          description: An account
          required: true
          type: string
        - name: count
          in: query
          description: Count of last transactions to return
          required: false
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Transactions"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: "Appends transaction to the buffer"
      parameters:
        - name: body
          in: body
          description: A transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "201":
          description: Added transaction to the buffer
          schema:
            $ref: "#/definitions/Transaction"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /blocks:
    x-swagger-router-controller: blocks
    get:
      description: Returns list of current blocks in the blockchain
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Blocks"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: "Mines a new block and adds it to the blockchain"
      operationId: mine
      parameters:
        - name: body
          in: body
          description: A miner config (should be protected by admin credentials)
          required: true
          schema:
            $ref: "#/definitions/Miner"
      responses:
        "201":
          description: Just mined block
          schema:
            $ref: "#/definitions/Block"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Account:
    type: string
    minLength: 5
  Amount:
    type: number
    minimum: 0
  Transaction:
    required:
      - to
      - from
      - amount
    properties:
      to:
        $ref: "#/definitions/Account"
      from:
        $ref: "#/definitions/Account"
      amount:
        $ref: "#/definitions/Amount"
  Transactions:
    required:
      - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Transaction"
  BlockHash:
    type: string
    minLength: 64
    maxLength: 64
  Block:
    required:
      - index
      - timestamp
      - data
      - hash
    properties:
      index:
        type: integer
      timestamp:
        type: string
      data:
        properties:
          transactions:
            type: array
            items:
              $ref: "#/definitions/Transaction"
          proof-of-work:
            type: number
      hash:
        $ref: "#/definitions/BlockHash"
  Blocks:
    type: array
    items:
      $ref: "#/definitions/Block"
  Miner:
    required:
      - account
    properties:
      account:
        $ref: "#/definitions/Account"
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
